env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: donwload
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: donwload
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - run: chmod +x build-app.sh
      - run: build-app.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build-artifact
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [Build, Test]
    steps:
      - name: donwload Build artifact
        uses: actions/download-artifact@v2
        with:
          name: Build-artifact
      - run: export GIT_COMMIT="GA-$GITHUB_SHA"
      - run: chmod +x ci/build-docker.sh 
      - run: chmod +x ci/push-docker.sh
      - run: ci/build-docker.sh
      - run: ci/push-docker.sh